### ISSUE TITLE
Remove unnecessary nesting (looping) in forms schema

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/mss-catalog-pilot#15]
It looks like some of our elements are allowing too much nesting which is creating problems for #10. E.g. idno inside idno and persName inside persName. 

Could you try to find these and restrict them to only the nesting that is absolutely necessary? 

I believe it might be just a matter of adding a content statement to the elementSpec, such as 
```
<content>
    <textNode/>
</content>
```
for idno. But I can't test this due to transformation problems I have right now for ODD to RNG.

**Comment by mMoliere** [comment]
I'll get on it.

**Comment by nathangibson** [comment]
Thanks!

**Comment by mMoliere** [comment]
If figured out how to restrict the nesting with the procedure you described. Applying it to `idno` and `persName` was sufficient to compile the RNG file.

**Comment by nathangibson** [comment]
Excellent, thanks! Do you discover any other possible endless loops like those? If not, you can close this issue.

**Comment by mMoliere** [comment]
Nothing came up when I compiled. So, I hope that this problem is resolved.
