### ISSUE TITLE
Elements missing which are allowed in schema

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/mss-catalog-pilot#24]
E.g., where is the author element? (perhaps other elements allowed in schema but not visible here?)

**Comment by wsalesky** [comment]
@nathangibson Can you be more specific? Where is the author element on which form, under which element?

**Comment by nathangibson** [comment]
For example, according to the schema, author is allowed as a child of msItem. But in the form it doesn't show up in the list of available elements to add.

**Comment by nathangibson** [comment]
@wsalesky Any idea what's going on here?

**Comment by wsalesky** [comment]
@nathangibson I think this is fixed, but we will need to double check on new forms. Leaving open for now.
