### ISSUE TITLE
Do we need to use template TEI files to pre-fill/pre-construct blocks that we expect to commonly use? 

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/mss-catalog-pilot#28]
Or is the schema alone adequate?

**Comment by wsalesky** [comment]
yes, this would be the fastest way.

**Comment by nathangibson** [comment]
@wsalesky OK, let me get this straight: 

- The schema we've been working on would be used to determine what is allowed and available to add via the form, as well as what is not allowed = not available or should be caught in errors (#29).
- We can use files with pre-filled TEI blocks (as you're doing now with the template) to show to the user, e.g., here's an msItem with a locus, title, and textLang. I.e., This is the minimum we expect you to fill out and it fulfills the minimum requirements for the schema. 

A **question**: should we have 1 pre-filled TEI file per project, and your forms module selects the correct elements to display (e.g., msItem for the contents module)? Or should we have 1 per module per project? 

And an **idea**: I think it would make sense to have a "new" button on blocks that are allowed to occur more than once, like msItem, to be able to easily add groups of things e.g. msItem with locus, title, and textLang to the record. This could be done on the basis of the blocks in the pre-filled files. What do you both think?

**Comment by nathangibson** [comment]
@wsalesky What do you think of this?

**Comment by wsalesky** [comment]
@nathangibson I think this can be closed? We are using the templates for pre-filled example content.
