### ISSUE TITLE
Investigate whether there’s any way to limit nesting in the schema

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/mss-catalog-pilot#31]
Otherwise, would another option be to hard-code into the XSLT that no elements (not just msItem) are self-nested more than say 3 times? It’s hard for me to imagine a scenario where we would want more than 3 levels and still be editing it in the forms rather than directly in TEI.

**Comment by mMoliere** [comment]
As far as I grasp the matter, it is a matter of manipulating the definition of [`model.msItemPart`](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-model.msItemPart.html). It lists all the elements which `msItem` can contain. Among many other things it also features `msItem` itself, which is the reason that self-nesting of `msItem` is allowed in our schema. If we wanted to prohibit self-nesting of `msItem` completely, I would suggest that we redefine `model.msItemPart` by removing `msItem`. Or do we anticipate cases where we want self-nesting to occur?

**Comment by nathangibson** [comment]
@mMoliere I do anticipate needing nested msItems. It's just that we don't need an infinite number. Perhaps 2-3. 

For Syriaca.org we often had cases where we wanted something like a "Genesis" msItem inside "Pentateuch". 

Would there be a way for example to allow msItem inside msItem but _not_ allow msItem inside msItem inside msItem? Do we have to resort to schematron rules inside the ODD for that?

**Comment by mMoliere** [comment]
@nathangibson The problem is that TEI does not put a cap on how many msItems can be nested inside each other. Unless I have overlooked something, we have to resort to schematron rules.

**Comment by wsalesky** [comment]
I think this is fixed with the more tightly constrained schemas
