### ISSUE TITLE
Forms not working in Firefox

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/mss-catalog-pilot#32]
The forms don’t load in my Firefox, only Chrome. Maybe this has to do with the following console message, which is the German equivalent of: „Synchronous XMLHttpRequests on the main thread should not be used anymore, since it has negative effects for the end-user experience. For more help see http://xhr.spec.whatwg.org/.“

**Comment by wsalesky** [comment]
@wsalesky Note to self, this appears to be a namespace issue in XForms controls, such as repeats and inputs. More debugging required.

**Comment by wsalesky** [comment]
Fixed in latest version of the forms.
