### ISSUE TITLE
Test out Hebrew labels

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/mss-catalog-pilot#33]
by adding `elementSpec/gloss[@xml:lang='he']` cf. #9

**Comment by wsalesky** [comment]
Added, will be available for testing next week. (Note to self, check local vrs global schema)

**Comment by wsalesky** [comment]
There are no Hebrew labels in any of the Schemas, if they are added to the schema, the forms should pick them up.

**Comment by wsalesky** [comment]
Tested with French labels, which are in the schema
