### ISSUE TITLE
Create preliminary form on basis of current schema

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/mss-catalog-pilot#5]
@wsalesky , could we ask you to go ahead and generate a manuscript description form on the basis of the https://github.com/biblia-arabica/mss-catalog-pilot/blob/main/schemas/mss.xml ODD file? (Or do you need the RNG?) 

I realize that this will probably be a mess since we haven't yet tuned that schema for the limited options we want in the form, nevertheless it would give us a starting point and help us figure out what we need to do vs what needs to be done from your side.  Thanks!

**Comment by wsalesky** [comment]
@nathangibson I will try to have something up on the test server by the end of next week. It may not be pretty, but at least you can get an idea of what  how it may look and function.

**Comment by nathangibson** [comment]
Wonderful, thanks!
