### ISSUE TITLE
Workaround for lacking drag-n-drop functionality

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/mss-catalog-pilot#52]
@wsalesky We're wondering what kind of workaround we might be able to do for changing the order of elements? 

E.g., instead of just delete button could there be a cut button that puts the XML into the clipboard and a paste button to insert it elsewhere? Some kind of error checking might be needed.

**Comment by wsalesky** [comment]
@nathangibson looking into this.

**Comment by wsalesky** [comment]
@nathangibson @mMoliere I don't think this can be done. I have been doing a lot hacking around on the XForms and so far it is not possible to break up the repeated elements. Please let me know if you want me to keep working on the XForms, or if this is a project stopping bug.
