### ISSUE TITLE
Bugs in Schemas/XForms

### ISSUE THREAD

**Issue by mMoliere** [biblia-arabica/mss-catalog-pilot#55]
**MSS Contents:**

`<msItem/> @class` missing
`<title/> @ref and @xml:lang` missing

**MSS Support:**

`<locus/> @target` missing
`<origDate/> @when, @from, @to` missing

**Hand:**

`<handNote/> @scope` missing
`<origDate/> @when` missing

**History:**

`<acquisition/>` missing

**Person:**

`<person/> @xml:id` missing

`<persName/> @xml:id, @xml:lang, @source, @resp` missing

`<birth/> @source` missing

`<death/> @source` missing

`<date/> @when, @notBefore, @notAfter` missing, `@calender, @type` displayed

`<floruit/> @when, @notBefore, @notAfter, @source` missing, 

`<sex/> @source` missing

`<occupation/> @type, @source` missing

`<residence/> @source` missing

`<bibl/> @xml:id` missing

The elements `<listRelation/>, <relation/>`, and `<desc/> `are missing.

**Comment by wsalesky** [comment]
@mMoliere Thanks! I will take a look and see what the XSLT is missing.

**Comment by mMoliere** [comment]
@wsalesky Excellent! The missing elements and attributes can now be selected and added to the description.

However, some elements now display a long list of attributes that are not found in our schema.

I list the elements that show this behavior at the begin of each section followed by some other bugs:

**MSS Contents:**

`msContents, summary, locus, mainLang, q, p, incipit, rubric, finalRubric, mItem, explicit, colophon, note`

**MSS Support:**

`supportDesc, support, extent, dimension, foliation`

Elements still grouped together rather than distributed according to template?

**Layout Description:**

Doesn't load

**Hand:**

`handDesc, handNote, persName, placeName, metamark, origDate`

locus: still missing attributes 

**Additions:**

`additions, p`

**Binding:**

Not listed in side panel.

**History:**
`history, origin, q, origPlace, origPlace, persName, provenance, signatures, stamp`

`acquisition`-element is still missing.

**Person:**

`persName, date, placeName, addName, forename, bibl, idno, citedRange`

`person @xml:id` missing

`persName` has no entry field

`addName @ref` missing

`date @source` missing

`floruit @from, @to, @notBefore, @notAfter `missing

`sex: @value, @source` missing

**Relation:**

`relation: @active, @passive, @source` missing

**Comment by wsalesky** [comment]
@mMoliere lets narrow it down to 1 element and the attributes that it should not be showing. You pick which element, let me know which attributes are showing up that should not be, and I will see why the XSLT is grabbing those attributes.

**Comment by mMoliere** [comment]
@wsalesky Good idea. 

**MSS Contents:**

`summary` should not display any attributes.

**Comment by wsalesky** [comment]
@mMoliere can you tell me which attributes you expect to see for 
**Hand**
`locus`

**Comment by mMoliere** [comment]
@wsalesky We want `@from` and `@to`

**Comment by wsalesky** [comment]
@mMoliere okay, thanks for the help debugging. I should have fixes for most of these up by tomorrow.

**Comment by mMoliere** [comment]
@wsalesky Thanks!

**Comment by wsalesky** [comment]
@mMoliere  just a few small issues in the persons schema: 
https://github.com/biblia-arabica/mss-catalog-pilot/blob/main/schemas/persons.xml#L467

the attDefs are outside the attList (which is why they are not showing up on the form)

Also, surname is not defined in the person.xml schema, and there are some duplicates here: 
https://github.com/biblia-arabica/mss-catalog-pilot/blob/main/schemas/persons.xml#L137

**Comment by mMoliere** [comment]
@wsalesky Thank you for alerting me to these oversights. I shall fix these issues ASAP.

My understanding of the global schema is that it only applies to the manuscript descriptions not the persons-entities. The global schema does not reflect the individual modules. (In fact, I haven't touched the global schema since July, as I believed that this file was no longer relevant to us. Cf. your email on January 11)

**Comment by wsalesky** [comment]
@mMoliere The way the form generator works is it first looks at the 'local' schema, the individual schemas you have been making. If it does not find any element or class rules in that module it needs to look up the rules in the 'global' schema, which should be a full output of the TEI schema. 

I have not used Roma in the past, so I don't have an opinion one way or the other.  I will reload the schema and regenerate the forms. I think the last big issue is the order of the elements. I have a few things to test today, but I do not know if it is possible to break up repeating elements.

**Comment by wsalesky** [comment]
@mMoliere Updated forms are on the website. Will be working on moving elements input positions today.

**Comment by wsalesky** [comment]
Closing this as it has been superseded by other issues.
