### ISSUE TITLE
ADD Identifier Module to XForms

### ISSUE THREAD

**Issue by mMoliere** [biblia-arabica/mss-catalog-pilot#61]
Between the "Title" and "Contents" we need another one: "Identifier". Based on msIdentifier – I added a template and schema to the usual folder.

**Comment by wsalesky** [comment]
@mMoliere I have added this locally, but it seems that the template includes some elements that are not referenced in the schema: 

```
<msIdentifier>
                        <country/>
                        <settlement/>
                        <institution/>
                        <repository/>
                        <idno/>
                        <msName/>
                        <altIdentifier type="IMHM">
                            <idno/>
                        </altIdentifier>
                        <altIdentifier type="SfarData">
                            <idno/>
                        </altIdentifier>
                        <altIdentifier type="Ktiv">
                            <idno/>
                        </altIdentifier>
                    </msIdentifier>
```

Notably country and settlement. They should either be removed from the template or added to the schema under msIdentifier. Thanks!

**Comment by mMoliere** [comment]
This is strange. When I open the schema, the country and settlement elements are there.
