### ISSUE TITLE
Specify working blocks for ms description forms

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/mss-catalog-pilot#7]

**Comment by nathangibson** [comment]
@wsalesky Here is a crude description of the individual forms I think we'd want in a modularized system. @rvollandt , @PietroLiuzzo , @mMoliere , would you agree?

The description here is meant to help you get an idea how you might structure it even though you'll still be waiting on schemas for these. Would it perhaps make sense for each of these forms to have a hard-coded "base" element the XSLT looks for in the schema (such as msContents) and then generate the fields based on what is allowed in that base element? 

**Step 1**: User selects an existing manuscript part to describe (with corresponding URI) or entire manuscript (if the msDesc has no child msPart) or creates a new one, thus  
- Form for creating a **new manuscript** description document: /TEI/teiHeader/fileDesc/msDesc containing 1 msIdentifier element (URI and shelfmarks) followed by 0-∞ msPart elements, each containing 1 msIdentifier with its own URI. 1 `history` and 1 `additional` element can optionally be added to the whole manuscript (msDesc) or each part (msPart). 

**Step 2**: User describes one of the following aspects of the selected manuscript part. The base elements/container elements below should go inside msPart, or if there are no msParts then directly inside msDesc.

- Form for describing **text contents**: 1 msContents, primarily containing multiple, nest-able msItem elements.
- Form for describing the **support**: 1 physDesc/objectDesc/supportDesc, which includes support, extent, foliation, collation, and condition
- Form for describing the **layout**: 1 physDesc/objectDesc/layoutDesc containing multiple (?) layout elements
- Form for describing the **hands and script**: 1 physDesc/handDesc containing multiple handNotes + 1 physDesc/scriptDesc containing multiple scriptNotes. (If it's too complicated to have 2 base elements here we could break it into 2 forms.)
- Form for describing **scribal additions**: 1 physDesc/additions/list containing multiple item elements. 
- Form for describing the **binding**: 1 physDesc/bindingDesc containing multiple binding elements.

Note: /TEI/teiHeader/fileDesc/publicationStmt, /TEI/teiHeader/encodingDesc, /TEI/teiHeader/profileDesc, and /TEI/teiHeader/revisionDesc need no form as they should be fully auto-generated based on the templates for each project.

**Comment by mMoliere** [comment]
@nathangibson I think this describes a very clear user interface that accommodates different scholarly specializations in a sensible manner. Just one detail: Are `msDesc` and `msPart` sufficient for our purposes? TEI also provides an element dedicated to fragments (`msFrag`). Should this element also be available to users, or will we express fragments in some other way (through attributes etc.)?

**Comment by nathangibson** [comment]
Thanks @mMoliere . Yes, I was unsure about whether we need `msFrag`. Need to check with @rvollandt about that.

**Comment by nathangibson** [comment]
@rvollandt says we do want msFrag, so I've added it to the description above.

**Comment by nathangibson** [comment]
I'll close this but we can still refer back to it as needed.
