### ISSUE TITLE
Add Fuzzy Search

### ISSUE THREAD

**Issue by mMoliere** [biblia-arabica/mss-catalog-pilot#77]
At the moment the database search only finds records when the complete shelfmark number of a manuscript is entered as a search string. It would be convenient to be able to search for partial shelfmark number.

**Comment by mMoliere** [comment]
No, we did not realize that this was implemented. But that is what we need. I will close the issue.

**Comment by wsalesky** [comment]
Sorry! I should have mentioned that those were available options.
