### ISSUE TITLE
Records committed to Github are not ingested into manuForma

### ISSUE THREAD

**Issue by mMoliere** [biblia-arabica/mss-catalog-pilot#78]
During the workshop, we tried to add new records to manuForma by committing files to the GitHub repository. They were findable in manuForma. However, records created in manuForma can be added to the repository. I suppose this not a bug, but is a result of how manuForma is communicates with GitHub. Right? We were able to work around this by uploading files through the browser, but once we start got "into production", we want to add thousands of files that are prefilled with metadata to the repository.

**Comment by wsalesky** [comment]
Sorry, can you clarify? The records were not added to GitHub? Or not added to manuForma? How did you upload files via the browser? From manuForma, on the forms page?

**Comment by mMoliere** [comment]
Works fine now. Thanks!
